WhatsCookingGoodLooking/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cooking.urls', namespace='cooking')),
    path('user/', include('user.urls', namespace='user'))
]

cooking/urls.py
from django.urls import path
from cooking.views import IndexView

app_name = 'cooking'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

user/urls.py
from django.urls import path
from user.views import UserLoginView, SignUpView
from django.contrib.auth.views import LogoutView

app_name = 'user'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('sign_up/', SignUpView.as_view(), name='sign_up')
]

cooking/models.py
from django.db import models


class ReceiptStep(models.Model):
    name = models.CharField(max_length=128)
    required_elements = models.TextField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='product_images', null=True, blank=True)
    time_to_cook = models.TimeField(null=True, blank=True)

    def __str__(self):
        return f'Step: {self.name} || id: ({self.pk})'

    def __repr__(self):
        return f'Step: {self.name} || id: ({self.pk})'


class Receipt(ReceiptStep):
    steps = models.ManyToManyField(to='ReceiptStep', related_name='steps', through='StepsQueue', blank=True)

    def __str__(self):
        return f'Recipt: {self.name} || id: ({self.pk})'

    def __repr__(self):
        return f'Recipt: {self.name} || id: ({self.pk})'


class StepsQueue(models.Model):
    from_receipt = models.ForeignKey(to=Receipt, on_delete=models.CASCADE, null=False, blank=False,
                                     related_name='from_reciept')
    to_step = models.ForeignKey(to=ReceiptStep, on_delete=models.CASCADE, null=False, blank=False,
                                related_name='to_step')
    position_in_queue = models.PositiveSmallIntegerField(default=1)

    class Meta:
        unique_together = ('from_receipt', 'position_in_queue')

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

user/forms.py
from django import forms
from django.contrib.auth.forms import (AuthenticationForm, UserCreationForm)
from user.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(required=True, widget=forms.TextInput(attrs={
        'class': 'form__input',
        'type': "username",
        'placeholder': 'Name',
    }))
    password = forms.CharField(required=True, widget=forms.PasswordInput(attrs={
        'class': 'form__input',
        'type': "password",
        'placeholder': 'Password',
    }))

    class Meta:
        model = User
        fields = ("username", 'password')


class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(required=True, widget=forms.TextInput(attrs={
        'class': "form__input",
        'type': "text",
        'placeholder': "Name",
    }))
    email = forms.CharField(required=True, widget=forms.EmailInput(attrs={
        'class': "form__input",
        'type': "text",
        'placeholder': "Email",
    }))
    password1 = forms.CharField(required=True, widget=forms.PasswordInput(attrs={
        'class': "form__input",
        'type': "password",
        'placeholder': "Password",
    }))
    password2 = forms.CharField(required=True, widget=forms.PasswordInput(attrs={
        'class': "form__input",
        'type': "password",
        'placeholder': "Confirm password",
    }))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

cooking/views.py
from django.views.generic.base import TemplateView


class IndexView(TemplateView):
    template_name = 'base.html'

user/views.py
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView
from django.views.generic.edit import CreateView
from django.contrib.messages.views import SuccessMessageMixin
from user.mixins import TitleMixin
from user.forms import UserLoginForm, UserRegistrationForm
from user.models import User
from django.contrib import messages


class UserLoginView(TitleMixin, LoginView):
    template_name = 'user/login.html'
    form_class = UserLoginForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('cooking:index')
    title = 'Login'

    def get_success_url(self):
        return reverse_lazy('cooking:index')

    def form_invalid(self, form):
        messages.error(self.request, 'Invalid username or password')
        return self.render_to_response(self.get_context_data(form=form))


class SignUpView(TitleMixin, SuccessMessageMixin, CreateView):
    model = User
    template_name = 'user/sign_up.html'
    form_class = UserRegistrationForm
    success_url = reverse_lazy('users:login')
    success_message = "Successful Sign up!"
    title = 'Sign up'

templates/base.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
<head>
    <title>Whats cooking, good looking</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/my.css' %}">
</head>
<body>

<!-- Navigation bar -->

<nav>
    <div id="site_head">
        <a class="navbar-brand" href="#">WCGL</a>
        <div>
            <ul>
                <li><a href="#">Рандом</a></li>
                <li><a href="#">Поиск</a></li>
                 {% if user.is_authenticated %}
                <li>
                    <ul>
                        <li><a href="#">Профиль</a></li>
                        <li><a href="{% url 'admin:index' %}">Админ-панель</a></li>
                        <li><a href="{% url 'user:logout' %}">Выйти</a></li>
                    </ul>
                </li>
                {% else %}
                    <li><a href="{% url 'user:login' %}">Войти</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>


<!-- Content -->
{% block content %}
<div>Zdarova</div>
{% endblock content %}

<!-- Footer -->
<nav id="footer">
    <a href="http://github.com/heshegto" target="_blank">My git</a>
    |
    <a href="mailto:heshkin@gmail.com" target="_blank">My mail</a>
</nav>

</body>
</html>

templates/user/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>{{ title }}</title>
		<link
			href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css"
			rel="stylesheet"
		/>
        <link rel="stylesheet" href="{% static 'css/login.css' %}">

	</head>
	<body>
		<div class="container">
			<span class="form__title">{{ title }}</span>
			<form class="form" method="post">
                {% csrf_token %}
				{% block content %}{% endblock content %}
			</form>
		</div>
	</body>
</html>

templates/user/login.html
{% extends 'user/base.html' %}

{% block content %}
    <div class="form__group">
        <i class="ri-user-line form__icon"></i>
        {{ form.username }}
        <span class="form__bar"></span>
    </div>
    <div class="form__group">
        <i class="ri-lock-line form__icon"></i>
        {{ form.password }}
        <span class="form__bar"></span>
    </div>
    <input type="submit" class="form__button" value="Login"/>
    {% if field.errors %}
        <small>{{ field.errors|striptags }}</small>
    {% endif %}
    <p class="form__switch">
        Don't have an account? <a href="{% url 'user:sign_up' %}">Sign up</a>
    </p>
{% endblock content %}

templates/user/sign_up.html
{% extends 'user/base.html' %}

{% block content %}
    <div class="form__group">
        <i class="ri-user-line form__icon"></i>
        {{ form.username }}
        <span class="form__bar"></span>
    </div>
    <div class="form__group">
        <i class="ri-mail-line form__icon"></i>
        {{ form.email }}
        <span class="form__bar"></span>
    </div>
    <div class="form__group">
        <i class="ri-lock-line form__icon"></i>
        {{ form.password1 }}
        <span class="form__bar"></span>
    </div>
    <div class="form__group">
        <i class="ri-lock-line form__icon"></i>
        {{ form.password2 }}
        <span class="form__bar"></span>
    </div>
    <button type="submit" class="form__button">Sign up</button>
    <p class="form__switch">
        Already have an account? <a href="{% url 'user:login' %}">Login</a>
    </p>
{% endblock content %}